# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.517
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.517/fabric_Windows_i386.zip
  InstallerSha256: F6169DD4EB6E34BB2AA3056D3ABAB282B144DE53260AFB28E3ED556641F9A7E7
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.517/fabric_Windows_x86_64.zip
  InstallerSha256: 71E9A4C5B2A008A45471DCA14997182E1783A3723EE32B11593A81781D653C0A
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.517/fabric_Windows_arm64.zip
  InstallerSha256: FE82CA719AEE6D8AAA1EC7F416F07635D44C669247AA9DCA53FBC821172236F7
ManifestType: installer
ManifestVersion: 1.12.0
