# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.496
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.496/fabric_Windows_i386.zip
  InstallerSha256: 7DE2C7FC4C4F0544B51F56D4C942D56E1BC7CF124F7EA9166EA09B436045BA72
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.496/fabric_Windows_x86_64.zip
  InstallerSha256: D81D7C7131F50D6E062EBDE67D2CB2AA09995C9460C203AA82177CB7451A2255
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.496/fabric_Windows_arm64.zip
  InstallerSha256: 11B26132FBF21A2CD68E25FCC63DE810177154AC76966FFAB7EBCD7ED51A549A
ManifestType: installer
ManifestVersion: 1.12.0
