# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.513
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.513/fabric_Windows_i386.zip
  InstallerSha256: 05F38593CA152AEFACE4ECF40D0EA8CFDF2134A66550F4FEA426432EE30372BA
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.513/fabric_Windows_x86_64.zip
  InstallerSha256: A9FE2DF9CE65CDEC1E6726C65D4D4B1B92D2F8CBCC9ECFA2AC290269C909D447
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.513/fabric_Windows_arm64.zip
  InstallerSha256: 130FF1ADC6433620368F2662ACE6F349AF34706958B1B5751490F45793A21BD3
ManifestType: installer
ManifestVersion: 1.12.0
