# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.512
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.512/fabric_Windows_i386.zip
  InstallerSha256: CF1FF6B9F4622A94BA86DB8AE9109213000BFBC41E948F69CD921B1CB0F65796
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.512/fabric_Windows_x86_64.zip
  InstallerSha256: C68604520AEE5AB48A7F084C53D6FA4013314C692602D70C9D0A1D772FECC8D6
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.512/fabric_Windows_arm64.zip
  InstallerSha256: 23DA41CE46917113EC6D9299CD1E12DD620B7328A23A081B58E26E7C79243163
ManifestType: installer
ManifestVersion: 1.12.0
