# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.515
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.515/fabric_Windows_i386.zip
  InstallerSha256: DBED70BA66EF3B4D736B877265F9C49061AA8B0277118AEC4148A73B14467BCF
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.515/fabric_Windows_x86_64.zip
  InstallerSha256: 2EDD648153DB133C1F177A8B0BA758303B8E94B76A1FCDBF9FF0FA97259E34FF
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.515/fabric_Windows_arm64.zip
  InstallerSha256: 87170A0429FFD5AAB3D54B61C569E112D7540D827605625E8881D0F5B5DC7349
ManifestType: installer
ManifestVersion: 1.12.0
