# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.511
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.511/fabric_Windows_i386.zip
  InstallerSha256: 1381802E51FECE4072A900C5FA94189C2FD9C61865E22F497E0D6DB328ED05D4
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.511/fabric_Windows_x86_64.zip
  InstallerSha256: F1BA71DB0F6A16C45F389E6BAE68095A00A83DB768BE182AF3B99340B44513A1
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.511/fabric_Windows_arm64.zip
  InstallerSha256: F8A42D48F7686EBE07AF1D10F8723E8669901874B70A356C750074A0E58EEDDA
ManifestType: installer
ManifestVersion: 1.12.0
