# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.505
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.505/fabric_Windows_i386.zip
  InstallerSha256: 2E7915456D2D31196138EF6AE99F75AD6889E2D13FDE62A6B18FCACA55017E3F
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.505/fabric_Windows_x86_64.zip
  InstallerSha256: 1A3CF774E13A211913465FC69EE18789ED4FA50331D6E912268319AB9C4FF6B6
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.505/fabric_Windows_arm64.zip
  InstallerSha256: 5C4F04A6A7939B57BB0443425AB2B0F7F41AD27AFBB9004E4911C92F993FD72B
ManifestType: installer
ManifestVersion: 1.12.0
