# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.509
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.509/fabric_Windows_i386.zip
  InstallerSha256: A6C3F36EB4ABE6B3664A8F61D3BA954061E61B8167CAD3DB85F9D3BA917E98F2
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.509/fabric_Windows_x86_64.zip
  InstallerSha256: 4EEBBC907AC952104EF948C7BC71A6C9EE7E030E230CD57CCFC442A1BFC3CE46
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.509/fabric_Windows_arm64.zip
  InstallerSha256: 71059EF718CB1ACED67B9A5FB8B62082380F62E72D72F5292704987FE3CA0ABB
ManifestType: installer
ManifestVersion: 1.12.0
