# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.507
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.507/fabric_Windows_i386.zip
  InstallerSha256: 12A8B07AEF76C1532F9E875DF8C5D3ABBE8B49F0A9AD5A564C67950A4756BA49
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.507/fabric_Windows_x86_64.zip
  InstallerSha256: DC7A827FD1165EBFC90C9F3C89783C377881817B1538F7BEB6DED5F8F114D81B
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.507/fabric_Windows_arm64.zip
  InstallerSha256: BFFB0F1F1A2D31D2F80EC23FC04C0CC320E5D9B01D37B92E2492185B69170422
ManifestType: installer
ManifestVersion: 1.12.0
