# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.508
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.508/fabric_Windows_i386.zip
  InstallerSha256: A94834B3D67D7968E2E5A3EC8A8D74AB947663852E3A08C8DE5D98921C0BC496
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.508/fabric_Windows_x86_64.zip
  InstallerSha256: C66DCA20549AC8A400BFB0EF0AA49FF261DFE6D707E7FB7DD6149E2EB71AAADE
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.508/fabric_Windows_arm64.zip
  InstallerSha256: FA14A216D6C49A44CB1D109AB94019990DB6001D732E925C43CC24833378568B
ManifestType: installer
ManifestVersion: 1.12.0
