# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: danielmiessler.Fabric
PackageVersion: 1.4.516
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fabric.exe
Commands:
- fabric
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.516/fabric_Windows_i386.zip
  InstallerSha256: 3C33AE7023533F33FF80459B841BE6FA0F8F6C42B9D332A8FAAEC875DA415941
- Architecture: x64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.516/fabric_Windows_x86_64.zip
  InstallerSha256: D57DDCA048DEEA9C285113035956E526EA613B09A6B6CF77249D9BB101E08447
- Architecture: arm64
  InstallerUrl: https://github.com/danielmiessler/Fabric/releases/download/v1.4.516/fabric_Windows_arm64.zip
  InstallerSha256: 1479FB2401114F42BEB47055A8B93439C33D154B339A071EEDBCB8367CC90142
ManifestType: installer
ManifestVersion: 1.12.0
